name: Merge Web Pages

on:
  schedule:
    - cron: '0 0 * * 3'  # Adjust the schedule as needed

jobs:
  merge-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Merge Web Pages
      run: python merge_pages.py

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Merge web pages
        file_pattern: output/*.txt
